version: "3"

services:
    web:
        build:
            context: ./
            dockerfile: web.Dockerfile
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./src:/var/www/html
        depends_on: 
            - db
        links:
            - db
        restart: always
    db:
        build:
            context: ./
            dockerfile: db.Dockerfile
        expose:
        - 3306
        ports:
        - "3306:3306"
        restart: always