version: "2.1"

services:
    web:
        container_name: plivo_web
        build:
            context: ./
            dockerfile: web.Dockerfile
        networks:
            - plivo_network
        ports:
            - "80:80"
        depends_on: 
            db:
                condition: service_healthy
        restart: always
    db:
        container_name: plivo_db
        build:
            context: ./
            dockerfile: db.Dockerfile
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        networks:
            - plivo_network
        ports:
        - "3306:3306"
        volumes:
            - plivo_volume:/var/lib/mysql
        restart: always
        healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u $$DB_USERNAME --password=$$DB_PASSWORD

volumes:
    plivo_volume:

networks:
    plivo_network:
        driver: bridge