version: "3"

services:
    web:
        build:
            context: ./
            dockerfile: web.Dockerfile
        expose:
        - 80
        - 443
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./src:/usr/local/apache2/htdocs
        depends_on: 
            - db
        links:
            - db
        restart: always
    db:
        build:
            context: ./
            dockerfile: db.Dockerfile
        environment: 
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        expose:
        - 3306
        ports:
        - "3306:3306"
        restart: always